deployment:
  imageURL: 850960379432.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue
  imageVersion: 1.0.0
hpa:
  maxReplicas: 10
  Utilization: 75
configMap:
  MONGO_URL: mongodb://mongodb:27017/catalogue